In [2]:
class Employee:
    # Creating a data member to count the number of Employees
    no_of_employees = 0
    # Initializing name, family, salary, department

    def __init__(self, name, family_name, salary, department):
        self.__name = name
        self.__family_name = family_name
        self.salary = salary
        self.__department = department
        Employee.no_of_employees += 1
     #Creating a function to average salary
    @staticmethod
    def average_salary(employees):
        sum = 0
        for employee in employees:
            sum += employee.salary
        return sum / Employee.no_of_employees
      #Creating a Fulltime Employee class
class FulltimeEmployee(Employee):
    def __init__(self, name, family_name, salary, department):
        super().__init__(name, family_name, salary, department)
    def full_time_benefits(self):
        print("Few benefits as full time employee.")
# Creating the instances of Fulltime Employee class and Employee class and also calling their member functions.
def main():
    employees = []
    fte1 = FulltimeEmployee("Employee1", "FamilyName1", 130000, "Management")
    fte1.full_time_benefits()
    employees.append(fte1)
    fte2 = FulltimeEmployee("Employee2", "FamilyName2", 200000, "RnD")
    employees.append(fte2)
    emp1 = Employee("Employee3", "FamilyName3", 180000, "Marketing")
    employees.append(emp1)
    emp2 = Employee("Employee4", "FamilyName4", 145000, "HR")
    employees.append(emp2)
    print("Average salary:", FulltimeEmployee.average_salary(employees))

if __name__ == "__main__":
    main()


Few benefits as full time employee.
Average salary: 163750.0


In [3]:
import numpy as np

#Creating a random vector of size 20
v = np.random.uniform(1, 20, 20)

v = v. reshape(4, 5)  # Reshape the array to 4 by 5

print(v)

v[np.arange(4), v.argmax(axis=1)]=0 # Replace the max value with 0 (axis=1)
print(v)


[[ 4.84261277  4.47661723  1.59690016 10.07036674 17.03426337]
 [13.48046362  6.85322146 13.19054386 17.86265611 11.97630349]
 [ 1.55862204 13.69914291 18.92879603 19.7924077   1.79859625]
 [ 6.9021605   7.227354    6.14842717 16.65825659  8.95565875]]
[[ 4.84261277  4.47661723  1.59690016 10.07036674  0.        ]
 [13.48046362  6.85322146 13.19054386  0.         11.97630349]
 [ 1.55862204 13.69914291 18.92879603  0.          1.79859625]
 [ 6.9021605   7.227354    6.14842717  0.          8.95565875]]
